### ISSUE TITLE
Error when loading AquaNet controller

### ISSUE THREAD

**Issue by gegy1000** [Team-Rapture/Aquatic#2]
```
[10:17:44] [Server thread/ERROR] [net.minecraft.tileentity.TileEntity]: Failed to load data for block entity aquatic:aquanet_controller
java.lang.NullPointerException: null
	at com.github.rapture.aquatic.util.TileEntityBase.func_70296_d(TileEntityBase.java:21) ~[TileEntityBase.class:1.0.0-b]
	at com.github.rapture.aquatic.tileentity.TileAquaNetController.setGeneratingOxygen(TileAquaNetController.java:124) ~[TileAquaNetController.class:1.0.0-b]
	at com.github.rapture.aquatic.tileentity.TileAquaNetController.func_145839_a(TileAquaNetController.java:36) ~[TileAquaNetController.class:1.0.0-b]
	at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:120) [avj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:494) [aye.class:?]
```

**Comment by gegy1000** [comment]
Looks like markDirty is being called in readFromNBT, which is too early because at that stage world is still null.

**Comment by UpcraftLP** [comment]
thanks for notifying gegy ^^
